apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-service
  labels:
    app: edge-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-service
  template:
    metadata:
      labels:
        app: edge-service
    spec:
      containers:
        - name: edge-service
          image: edge-service:0.0.1
          imagePullPolicy: IfNotPresent
          lifecycle: # makes kubernetes wait for 5 seconds before sending SIGTERM to the pod
            preStop:
              exec:
                command: [ 'sh', '-c', 'sleep 5' ]
          ports:
            - containerPort: 8135
          env:
            - name: ACTIVE_PROFILE
              value: 'dev'
            - name: SERVER_PORT
              value: '8081'
            - name: CONFIG_SERVER_URI
              value: 'configuration-service'
            - name: CONFIG_SERVER_PORT
              value: '80'
