apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-service
  labels:
    app: edge-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-service
  template:
    metadata:
      labels:
        app: edge-service
    spec:
      containers:
        - name: edge-service
          image: edge-service:0.0.1
          imagePullPolicy: IfNotPresent
          lifecycle: # makes kubernetes wait for 5 seconds before sending SIGTERM to the pod
            preStop:
              exec:
                command: [ 'sh', '-c', 'sleep 5' ]
          ports:
            - containerPort: 8135
          env:
            - name: ACTIVE_PROFILE
              value: 'dev'
            - name: SERVER_PORT
              value: '8081'
            - name: CONFIG_SERVER_URI
              value: 'configuration-service'
            - name: CONFIG_SERVER_PORT
              value: '80'
            - name: SERVER_CONNECTION_TIMEOUT
              value: '2s'
            - name: SERVER_IDLE_TIMEOUT
              value: '15s'
            - name: LIFECYCLE_TIMEOUT_PER_SHUTDOWN
              value: '15s'
            - name: CATALOG_SERVICE_URL
              value: 'http://localhost:8135'
            - name: ORDER_SERVICE_URL
              value: 'http://localhost:8136'
            - name: GATEWAY_HTTPCLIENT_POOL_MAX_IDLE_TIME
              value: '15s'
            - name: GATEWAY_HTTPCLIENT_POOL_MAX_LIFE_TIME
              value: '60s'
            - name: GATEWAY_HTTPCLIENT_CONNECT_TIMEOUT
              value: '2000'
            - name: GATEWAY_HTTPCLIENT_RESPONSE_TIMEOUT
              value: '5s'
            - name: RETRY_COUNT
              value: '3'
            - name: RETRY_FIRST_BACKOFF
              value: '50ms'
            - name: RETRY_MAX_BACKOFF
              value: '500ms'
            - name: RETRY_FACTOR
              value: '2'
